### ISSUE TITLE
Unsupported Uri when user choose a directory

### ISSUE THREAD

**Issue by shynline** [HBiSoft/PickiT#16]
I get Unsupported Uri for :  `content://com.android.providers.downloads.documents/tree/msd%3A11526`
when I choose a directory 
API 29
And I launch directory picker like this (in order to reproduce)

`val intent = Intent(ACTION_OPEN_DOCUMENT_TREE).apply {`
`putExtra(Intent.EXTRA_LOCAL_ONLY, true)`
`putExtra(EXTRA_SHOW_ADVANCED, true)`
 `}`
`fragment.startActivityForResult(intent, requestId)`

**Comment by HBiSoft** [comment]
"ACTION_OPEN_DOCUMENT_TREE" is currently not supported by this library.

What do you expect the library to return when you pass a `DocumentFile`? Do you want the path of all the files in the selected directory to be returned?

**Comment by shynline** [comment]
No the path of the directory itself
Like `/some_storage/download/the_folder`
I want to pass it to `File`

**Comment by HBiSoft** [comment]
I will not be implementing this becuase the only reliable way of getting the removable disk id requires API 24>.

Here is an example of how you can achieve this. I know it might not be the cleanest solution, but I've tested it and it works.

```java
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        Log.e("Test Path", getPath(data.getData()));
}

private String getPath(Uri uri) {
    String replaceChars = String.valueOf(uri).replace("%2F", "/").replace("%20", " ").replace("%3A",":").replace("tree/","");
    if(replaceChars.contains("primary:")){
        String root = "/storage/emulated/0/";
        return root+replaceChars.substring(replaceChars.indexOf("primary")).replace("primary:","");
    }
    if(replaceChars.contains("raw:")){
        return replaceChars.substring(replaceChars.indexOf("raw")).replace("raw:","");
    }
    String sdID = getSdId();
    if(sdID != null && replaceChars.contains(sdID)){
        String root = sdID+"/storage/emulated/0/";
        return root+replaceChars.substring(replaceChars.indexOf(sdID)).replace(sdID+":","");
    }
    return replaceChars;
}

private String getSdId(){
    String id = "";
    StorageManager storage= getSystemService(StorageManager.class);
    List<StorageVolume> volumes=storage.getStorageVolumes();
    for (StorageVolume volume : volumes) {
        if (volume.getUuid()!=null){
            id = volume.getUuid();
        }
    }
    return id;
}
```

The above with return something like this `/storage/emulated/0/SomeFolder`.

I did not do a comprehensive test, please let me know if it works for you.
I will be closing this issue since I will not be implementing this into the library.
