### ISSUE TITLE
File not found exception when picking file from downloads

### ISSUE THREAD

**Issue by enthussb** [HBiSoft/PickiT#25]
Whenever I select any file from downloads with filename containing spaces, it is giving me an error file not found exception & also a toast in a different language. Please provide a fix for this.

I have the traced the issue - it is due to invalid characters in the filename and we need to replace them with an underscore.

Android -10

**Comment by HBiSoft** [comment]
What is the path that gets returned and what is the file name?

Please provide a screenshot using the demo application.

**Comment by enthussb** [comment]
@HBiSoft I cannot capture the screenshot using the demo application as the downloads folder is disabled.

**Comment by HBiSoft** [comment]
>the downloads folder is disabled
I tested and I was able to select a file from the downloads folder.

Anyway, what is the file path that gets returned?

**Comment by enthussb** [comment]
Returned path by PickiT 

E/RETURNED -: /storage/emulated/0/Download/**Screenshot (94).png**
This path is not found when you try to create a file object as the actual file name is **screenshot__94_.png**

You can reproduce the issue by renaming the file with spaces or brackets and then check if the file exists using File Object.

**Comment by HBiSoft** [comment]
I tested this by selecting a file with the following name - **VID 2019__1234_.mp4** 
PickiT returned the following path - **/storage/emulated/0/Download/VID 2019__1234_.mp4**

I tested this:
```java
File mFile = new File(pathReturnedByPickiT);
if (mFile.exist){
    Log.e("File", "was found");
}
```
and the log gets called.

---
Can you please provide me with the `Uri` that gets returned in `onActivityResult` - `data.getData();`?

**Comment by enthussb** [comment]
> Can you please provide me with the `Uri` that gets returned in `onActivityResult` - `data.getData();`?
@HBiSoft 
Uri - content://com.android.providers.downloads.documents/document/475

![image](https://user-images.githubusercontent.com/29205181/89783986-7facc480-db35-11ea-98f7-61bdd8b71387.png)
![image](https://user-images.githubusercontent.com/29205181/89783998-8afff000-db35-11ea-998e-230453d7779d.png)

**Comment by sugatmankar** [comment]
If i download an zip and extracted it in Download folder
Download
|__Extracted
    |_File1
    |_File2

In this case if i selected File1

It returns /storage/emulated/0/Download/File1

It should have returned /storage/emulated/0/Download/Extracted/File1

**Comment by HBiSoft** [comment]
@enthussb 
Thats very strange because I'm not replacing characters in the file name.
Please try the following and see what name gets returned:

```java
@SuppressWarnings("TryFinallyCanBeTryWithResources")
private static String getFilePath(Context context, Uri uri) {
    Cursor cursor = null;
    final String[] projection = {MediaStore.Files.FileColumns.DISPLAY_NAME};
    try {
        cursor = context.getContentResolver().query(uri, projection, null, null, null);
        if (cursor != null && cursor.moveToFirst()) {
            final int index = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DISPLAY_NAME);
            return cursor.getString(index);
        }
    }catch (Exception e) {
        e.printStackTrace();
    } finally {
        if (cursor != null)
            cursor.close();
    }
    return null;
}

```

**Comment by HBiSoft** [comment]
@sugatmankar 
Are you using the latest version? I remember fixing this in an earlier release.
If you are using the latest version, please open a new issue and provide as much info as possible.
Thanks.

**Comment by enthussb** [comment]
> @enthussb
> That's very strange because I'm not replacing characters in the file name.
> Please try the following and see what name gets returned:

@HBiSoft 
![image](https://user-images.githubusercontent.com/29205181/89981019-b519f500-dc90-11ea-8d22-94d6ef79dec2.png)
This is the name returned by that function whereas the original name in the file manager is
![Screenshot_20200812-114146](https://user-images.githubusercontent.com/29205181/89981123-f27e8280-dc90-11ea-96d0-150e480fc77d.jpg)

Currently, I am facing this issue only when I pick any file from downloads.

**Comment by HBiSoft** [comment]
@enthussb 
I'm not able to reproduce this.
Please provide me your entire `Intent`, so that I can test it as you have it.

**Comment by enthussb** [comment]
@HBiSoft
`Intent` 
![image](https://user-images.githubusercontent.com/29205181/89997683-126e7000-dcaa-11ea-9284-311438fc8645.png)

**Comment by enthussb** [comment]
@HBiSoft 
> Please provide me your entire `Intent`, so that I can test it as you have it.
`final String[] ACCEPT_MIME_TYPES = {
                "application/pdf",
                "image/*"
        };
        Intent intent = new Intent()
                .setType("*/*")
                .setAction(Intent.ACTION_OPEN_DOCUMENT)
                .addCategory(Intent.CATEGORY_OPENABLE)
                .putExtra(Intent.EXTRA_MIME_TYPES, ACCEPT_MIME_TYPES);
        startActivityForResult(intent, REQUEST_SELECT_FILE);`

**Comment by HBiSoft** [comment]
I tested once more and I still was not able to reproduce this.
I'm not sure if [the following will give the correct name](https://developer.android.com/training/secure-file-sharing/retrieve-info), but it's worth the try, please let me know if the correct name is returned:

```java
@SuppressWarnings("TryFinallyCanBeTryWithResources")
private static String getFilePath(Context context, Uri uri) {
    Cursor cursor = null;
    try {
        cursor = context.getContentResolver().query(uri, null, null, null, null);
        if (cursor != null && cursor.moveToFirst()) {
            final int index = cursor.getColumnIndexOrThrow(OpenableColumns.DISPLAY_NAME);
            return cursor.getString(index);
        }
    }catch (Exception e) {
        e.printStackTrace();
    } finally {
        if (cursor != null)
            cursor.close();
    }
    return null;
}
```

**Comment by enthussb** [comment]
@HBiSoft 
I tested with the above code and still, I got the same name as the display name whereas the original name should have spaces replaced with underscores, or else it will give file not found exceptions.
![image](https://user-images.githubusercontent.com/29205181/90045395-9c3f2d00-dcec-11ea-8b6c-8949053d35f1.png)

**Comment by HBiSoft** [comment]
Can you please explain what you meant with the following:

>I cannot capture the screenshot using the demo application as the downloads folder is disabled.

Also, you said the following:

>from the downloads folder when you open the intent and not by going through file manager -> downloads -> file

I assume you meant that after launching the intent -> Files - Downloads - screenshot__94_.png?

**Comment by enthussb** [comment]
> Can you please explain what you meant with the following:

It is the same as #2 Whenever I try to pick a file from downloads using PickIt I am unable to do that as all the files are disabled there.

 > I assume you meant that after launching the intent -> Files - Downloads - screenshot__94_.png?

**There are two ways to go to downloads** - 

1. As shown in the below picture
2. By manually traversing through Internal Storage -> Downloads (File manager basically) 

Whenever I pick a file **having spaces or bracket in its name** from downloads using the **first method** I am getting File not found exception.

Hope this will make it clear.

![Screenshot_20200813-105839](https://user-images.githubusercontent.com/29205181/90098063-0d1a2f80-dd55-11ea-9bdc-4a9f08d5b757.jpg)

**Comment by HBiSoft** [comment]
@enthussb 
>It is the same as #2 Whenever I try to pick a file from downloads using PickIt I am unable to do that as all the files are disabled there.

No, video files are not disabled. In the demo application `intent.setType("video/*");` is passed to the `Intent`.
I wanted you to test with the demo application (by selecting a video) to see if the problem might be with the `Intent`.
Instead of selecting an image, rename a video inside your downloads folder to a similar name and test it again.

>Hope this will make it clear.

Yes, I tested both ways.

**Comment by enthussb** [comment]
@HBiSoft The issue is if you rename it from your file manager it will work as it corrects the file name. Could you provide me your email so that I can send you the image there and then after downloading it you can check the issue?

**Comment by HBiSoft** [comment]
@enthussb 
>The issue is if you rename it from your file manager it will work as it corrects the file name.

No, the issue is that an incorrect name is given when querying the `DISPLAY_NAME` column (this is not related to the library) and we will not be able to fix it afterwards (by renaming it) because how will we know that the name is incorrect..

---

>I wanted you to test with the demo application (by selecting a video) to see if the problem might be with the Intent.
Instead of selecting an image, rename a video inside your downloads folder to a similar name and test it again.

Did you test this?

---

>Could you provide me your email so that I can send you the image there and then after downloading it you can check the issue?

Sure here is my email - contact.hbisoft@gmail.com

PS. I did rename an image to `screenshot__94_.png` and selected if from the Downloads folder as you mentioned in https://github.com/HBiSoft/PickiT/issues/25#issuecomment-673271362

**Comment by enthussb** [comment]
@HBiSoft I checked with what you said and it works as file is renamed using the file manager but the problem which I am facing is different & I am unable to explain to you right now. Closing this temporarily
