### ISSUE TITLE
Help with multiple files

### ISSUE THREAD

**Issue by Parag2385** [HBiSoft/PickiT#27]
Hello, this is very great work.

I just have a problem/feature request, how could we get multiple file's real paths at once? As your using callbacks, you cannot call the pickit.getPath() method in loop, right?

So have you considered this scenario for your future releases? Or if you know any workaround for the same?

Thanks.

**Comment by HBiSoft** [comment]
Apologies for the late reply. 

I'm currently to busy to implement this, but I will look into implementing it in the next week or so.
If you want, you can implement it and create a pull request.

I will temporarily close this issue, I will notify you once I've implemented this.
