### ISSUE TITLE
Android Studio 3.3 - Adding PickiT library build.gradle fails

### ISSUE THREAD

**Issue by sourligas** [HBiSoft/PickiT#3]
Hi, 

By adding the PickiT library (implementation `com.github.HBiSoft:PickiT:0.1.6` ) on my project the build.gradle fails when it is trying to sync.

Do you have any idea why this is happening? Do you have any similar incident until now? Maybe it's a conflict with other existing implementations on my build.gradle? 

Please let me know how can I help you to send more information to investigate the issue in further.

**_Note:_** Awesome job from your side to create such a library for the community. Because it's a mess on Android how to handle the real path for a content Uri.

**Comment by HBiSoft** [comment]
Please provide your log when trying to sync your project. It should provide a reason why it's failing.

**Comment by sourligas** [comment]
I will do that later on today as soon as I will try to sync the project again and have the logs.

**Comment by HBiSoft** [comment]
I'm still waiting for your reply?

**Comment by sourligas** [comment]
I was not able to work on this project yesterday because of highest priority issues in another project. But I will do it today in the evening and send you the build logs. Sorry for this delay.

**Comment by sourligas** [comment]
Eventually, the issue is not related to your library. I have an issue with my project path name. 

`
What went wrong:
A problem occurred evaluating project ':app'.
Failed to apply plugin [id 'com.android.application']
Your project path contains non-ASCII characters. This will most likely cause the build to fail on Windows. Please move your project to adifferent directory.`

So, I will close this issue.

Thanks.
