### ISSUE TITLE
Selecting a recent image in gallery doesn't seem to work

### ISSUE THREAD

**Issue by ivanlares** [HBiSoft/PickiT#34]
Thank you for your work here. When selecting an image from Gallery everything works.

When selecting on a "recent image" the path returned in `PickiTonCompleteListener` is null.

**Full Log**
`path: null, wasDriveFile: false, wasUnknownProvider: false, wasSuccessful: false, reason: null`

In `onActivityResult` this is what I'm getting when selecting a "recent image":
`uri.path.toString()` : `/document/image:31`
`uri`: `content://com.android.providers.media.documents/document/image%3A31`

Build.Version is `30`

---

Is this expected behavior?

**Comment by HBiSoft** [comment]
Please download/install the [demo application](https://github.com/HBiSoft/PickiT/releases/download/0.1.14/PickiTDemo.apk) and check if it still returns `null`.

---

`content://com.android.providers.media.documents/document/image%3A31` is a valid `Uri` and should work.

I tested on my device, also running 30, and it works fine:

Uri - `content://com.android.providers.media.documents/document/image%3A64510`
Path returned in `onActivityResult` : `/storage/6330-6333/DCIM/Camera/testImage.jpg`

**Comment by ivanlares** [comment]
Hello @HBiSoft, I wasn't too sure how to run the APK file attached on my device. I realized the issue may be due to my use of the Android Virtual Device. I tested my application on a physical device and I got an error message. In the AVD there was no error message. Therefore I solved for the error (missing read permissions) and everything works as expected. Thank you
