### ISSUE TITLE
crash on recent image file

### ISSUE THREAD

**Issue by andrewindayang** [HBiSoft/PickiT#36]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1120, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:8585 flg=0x1 }}

is there any idea why the path is null????

i am using android 11

**Comment by andrewindayang** [comment]
i am really sorry, found the issue where the permission is not allowed. May be this can be a solution for user who face this problem. thank you.

**Comment by adigujjar** [comment]
@andrewindayang  i have the same issue which permission you added can you help me out
