### ISSUE TITLE
please do update for jcenter migration please

### ISSUE THREAD

**Issue by andrewindayang** [HBiSoft/PickiT#39]
please do update for jcenter migration please

**Comment by HBiSoft** [comment]
I'm not really sure what you are asking.

If you are asking me to migrate the project from maven to jcenter - [Jcenter is closing soon](https://blog.gradle.org/jcenter-shutdown#:~:text=On%20February%203%202021%2C%20JFrog,shutting%20down%20Bintray%20and%20JCenter.&text=run%20your%20code.-,Gradle%20may%20not%20be%20able%20to%20download%20the%20dependencies%20used,publish%20your%20package%20to%20Bintray.)

**Comment by andrewindayang** [comment]
hi, yes. jcenter is closing soon. May i know when are you gonna submit for update?

**Comment by HBiSoft** [comment]
What do you want me to update?

**Comment by andrewindayang** [comment]
before that sorry if i am wrong or not. But when i create new project and i didnt include jcenter() on gradle,  i tried to 
    implementation 'com.github.HBiSoft:PickiT:0.1.14'

and i got error due to the library need jcenter() on the gradle
