### ISSUE TITLE
Android 11 we can't fetch pdf file and store own path. Can you please check?

### ISSUE THREAD

**Issue by amitagnihotri** [HBiSoft/PickiT#40]
**Describe the bug**
- Please fill in all the information below.
- Have a look at previously asked questions to see if your issue has been resolved.
- Properly format your issue.
- All issues should be asked in English.
- Delete all the above before posting your issue

**Describe the bug**

**Log**
Please provide a well-formatted bug report (by adding 4 spaces before the log)

**Can it be reproduced in demo app**
Yes or no

**PickiT version**
for example 1.0.1

**Device information**
- Make/model
- SDK version

**Screenshots**

**Comment by HBiSoft** [comment]
Please see [Always fill in the issue template](https://github.com/HBiSoft/PickiT/issues/29).

Edit your issue and provide as much information as possible, the issue will be closed until you do.
