### ISSUE TITLE
Picking a file from  a subfolder inside downloads folder returns wrong path

### ISSUE THREAD

**Issue by el-Knix** [HBiSoft/PickiT#41]
**Describe the bug**
If you select a file that is inside a subfolder inside the downloads tab, pickit returns path of the file without the subfolder name.

**Can it be reproduced in demo app**
Yes 

**PickiT version**
0.1.14

**Device information**
- Huawei Mate 20 Pro
- 29

**Comment by Ammarulhaq** [comment]
@el-Knix I think this issue is not about pickIt SDK. I'd the same issue what actually happens is when we use download file function path is reference to "Download" directory what i did was i just  point my directory to  "Download/MY_FOLDER_NAME" and it worked

**Comment by HBiSoft** [comment]
@el-Knix 
I was able to reproduce this. The only way I can work around this is to check for the `msf:` protocol and copy the file to your apps directly.

@Ammarulhaq 
Can you please elaborate on what you mean with:
> i just point my directory to "Download/MY_FOLDER_NAME"

**Comment by el-Knix** [comment]
@HBiSoft That's the work around I'm currently using. Not ideal but I guess there's no choice.

**Comment by HBiSoft** [comment]
I've made the necessary changes and will implement it into the library tomorrow.

It will now first check for the `msf:` protocol, then check if the file is available in the Downloads directory, if not it means it's in a subdirectory inside the Downloads directory and gets copied into the applications directory.

I will keep looking for ways to do it without copying the file, but in the meantime this will have to suffice.

**Comment by el-Knix** [comment]
Thanks Mate that will have to do...Great work on the library!

**Comment by HBiSoft** [comment]
@el-Knix 
My apologies for the delay.

I have found a way to get the file without having to copy it, by using `/proc/`.
I have tested it on multiple devices, but it would be great if you can test it as well.

The latest release (2.0.1) is available [here](https://github.com/HBiSoft/PickiT/releases/tag/2.0.1).

---
Please close the issue after you have tested it.

**Comment by el-Knix** [comment]
@HBiSoft 
Just tested, seems to work great kudos.

Just one issue, the filename seems to be lost with this method since the proc path only has a number, any idea on how we can get the filename from the /proc/ path?

**Comment by HBiSoft** [comment]
@el-Knix 
You will have to make use of the original `Uri` that gets returned from `MediaStore`.

Here's how I do it inside the library:

https://github.com/HBiSoft/PickiT/blob/81e4601ba2a8ef9cd6a5ddaf1f21691dd3dccd8f/pickit/src/main/java/com/hbisoft/pickit/DownloadAsyncTask.java#L131-L153

**Comment by Suresh8900** [comment]
But whenever I send this path to my API it shows an error /storage/emulated/0/Download/demo.pdf: open failed: EACCES (Permission denied)
Only in the case of the download folder.
