### ISSUE TITLE
how can we pass Media store Id to get the file

### ISSUE THREAD

**Issue by pawaom** [HBiSoft/PickiT#42]
I am totally new to android 11 file access, 

I have a simple question , I have an activity where we get the Song Id using `MediaStore.Audio.Media._ID` , I want to pass it to an activity which uses `Jaudiotagger` for which I need the file using `File =  new File();` which is in a separate activity.

So from activity A I pass the Intent extra like this
```
Long ExtraVal = SongId ; // MediaStore.Audio.Media._ID 
 Intent myIntent = new Intent(mcontext, ActivityToOpen);
        myIntent.putExtra("ExtraVal", ExtraVal);
        mcontext.startActivity(myIntent);
```
and in Activity B , I get it Like this,
```
Bundle extras = getIntent().getExtras();
        if (extras == null) {
            ExtraVal = null;
        } else {
            ExtraVal = extras.getLong("ExtraVal");
        }
```

**How can I use this Id to get the file path and pass it to `File =  new File()`**

I am a total noob so please help 

Also  the `startActivityForResult(intent, SELECT_VIDEO_REQUEST)` is depreccated can you please update the example .

**Comment by HBiSoft** [comment]
Yes, `startActivityForResult(intent, SELECT_VIDEO_REQUEST)` is deprecated, but it's a demo application and it works as is. I will update it when I have the time.

As for your question, I'm not really sure what you are asking and if it's relevant to the library?

**Comment by pawaom** [comment]
can you please provide an example should I pass `ContentUris.withAppendedId(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,
                                songCursor.getLong(songCursor.getColumnIndexOrThrow(MediaStore.Audio.Media._ID))`
