### ISSUE TITLE
isUnknownProvider doesn't exist

### ISSUE THREAD

**Issue by selankon** [HBiSoft/PickiT#45]
**Is your feature request related to a problem? Please describe.**

Related to #44, you answered me that a method called `pickiT.isUnknownProvider` is exposed. Meanwhile, you didn't merge or push this change at master or any other place that I saw.

**Describe the solution you'd like**

Probably you push it somewhere else? Please could you specify where to find this method?

This issue is just a reminder of #44 because it seem you didn't receive my comments.

Thanks in advance!

**Comment by HBiSoft** [comment]
Hi @selankon 

My apologies for the delay. I will be updating the library today.

**Comment by selankon** [comment]
Hi!

What about this! Expecting :)

**Comment by HBiSoft** [comment]
Fixed in [2.0.3](https://github.com/HBiSoft/PickiT/releases/tag/2.0.3). Apologies for the delay.

**Comment by selankon** [comment]
thanks
