### ISSUE TITLE
Android- Crash on Android 9

### ISSUE THREAD

**Issue by ahmadbajwa8282** [HBiSoft/PickiT#50]
**Caused by java.lang.SecurityException**

> Permission Denial: reading com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri content://com.google.android.apps.docs.storage/document/acc%3D3%3Bdoc%3Dencoded%3Do64-UNpfLjl3z8K-7vho6s1Mbnr0UzMJ7rMp3BBn0-ummr0WCPWDUMQG40jDScPuID78 from pid=26080, uid=10380 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

> Caused by java.lang.SecurityException: Permission Denial: reading com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri content://com.google.android.apps.docs.storage/document/acc%3D3%3Bdoc%3Dencoded%3Do64-UNpfLjl3z8K-7vho6s1Mbnr0UzMJ7rMp3BBn0-ummr0WCPWDUMQG40jDScPuID78 from pid=26080, uid=10380 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
>        at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
>        at android.os.Parcel.createException(Parcel.java:2373)
>        at android.os.Parcel.readException(Parcel.java:2356)
>        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
>        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
>        at android.content.ContentProviderProxy.query(ContentProviderProxy.java:473)
>        at android.content.ContentResolver.query(ContentResolver.java:1192)
>        at android.content.ContentResolver.query(ContentResolver.java:1124)
>        at android.content.ContentResolver.query(ContentResolver.java:1080)
>        at com.hbisoft.pickit.DownloadAsyncTask.getFileName(DownloadAsyncTask.java:135)
>        at com.hbisoft.pickit.DownloadAsyncTask.doInBackground(DownloadAsyncTask.java:96)
>        at com.hbisoft.pickit.DownloadAsyncTask.doInBackground(DownloadAsyncTask.java:19)
>        at android.os.AsyncTask$3.call(AsyncTask.java:394)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>        at java.lang.Thread.run(Thread.java:923)

**Comment by HBiSoft** [comment]
The issue is described in the log:
```log
Caused by: java.lang.SecurityException: Permission Denial: reading com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri content://com.google.android.apps.docs.storage/document/acc%3D3%3Bdoc%3Dencoded%3Do64-UNpfLjl3z8K-7vho6s1Mbnr0UzMJ7rMp3BBn0-ummr0WCPWDUMQG40jDScPuID78 from pid=26080, uid=10380 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs.
```

You should use `ACTION_OPEN_DOCUMENT` instead of `ACTION_GET_CONTENT`

---

This issue was already opened here - #10 and #15
