### ISSUE TITLE
EAccess Denied to path on Android 11

### ISSUE THREAD

**Issue by bssit1745** [HBiSoft/PickiT#56]
While using library on android less than 10 its working fine but as you go above 11 it returns path but also show error EAccess Denied while picking pdf

**PickiT version**
 2.0.5

**Comment by HBiSoft** [comment]
Apologies for the late reply. This is most probably caused by not adding the following in your manifest:
```xml
<manifest ... >
  <application 
    android:requestLegacyExternalStorage="true" 
  </application>
</manifest>
```
If you are still having issues with this, please reopen the issue and provide more info on the issue.
Thanks

**Comment by viktorilievski** [comment]
_requestLegacyExternalStorage_ is not working on Android 11.

You must use a new permission as I have stated in this comment -> https://github.com/HBiSoft/PickiT/issues/55#issuecomment-1699052901
