### ISSUE TITLE
Issue for video from Recent folder on Android 13

### ISSUE THREAD

**Issue by nexus-niranj** [HBiSoft/PickiT#57]
I have set targetSdk 33 

When I pick video from recent (Android 13) then not getting path.
Sample URI: content://com.android.providers.media.documents/document/video%3A1000000041

If I will pick other document from recent folder (Android) then working and also started working previous file as well. 
Sample URI: content://com.android.providers.media.documents/document/document%3A1000000040

Issue: First time video path not receive from recent, if pick any other file then start working video. 

My sample code for pick file
```

Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true);
String [] mimeTypes = {"text/*", "application/*", "video/*", "audio/*"};
intent.setType("*/*");
intent.putExtra(Intent.EXTRA_MIME_TYPES, mimeTypes);
```

Tested sample APK and its working fine but I have targetSDK 33.

**Comment by HBiSoft** [comment]
Apologies for the late reply. The problem is with how you start your intent. Please have a look at the demo application.
