### ISSUE TITLE
When I record the screen before I can set When recording audio In addition to the three options you provided, can I set the input to record a live stream with a pure audio stream?

### ISSUE THREAD

**Issue by ILoveLin** [HBiSoft/PickiT#61]
When I record the screen before I can set
When recording audio In addition to the three options you provided, can I set the input to record a live stream with a pure audio stream?

Is it possible to add a function of this option, as shown in the figure
![adddd](https://github.com/HBiSoft/PickiT/assets/20768182/a6be42a4-2fd9-41da-afc4-eafc036ddcdd)

**Comment by HBiSoft** [comment]
Please open the issue on the correct library. This is related to `HBRecorder` and not `PickiT`
